### ISSUE TITLE
Avoid vertical scrolling

### ISSUE THREAD

**Issue by santhoshtr** [meenaviyal/comicmachine#25]
The webpage does not need scrollbars. Avoid scrolling and place the tools as fixed. The canvas, if user decide to expand, can be optionally scrollable

**Comment by hfactor** [comment]
This is a bug. I can't replicate in my machine. Could you please share your browser, screen resolution and OS details?

**Comment by santhoshtr** [comment]
1600 x 900, Chrome 51/Debian. But I think it does not matter. With smaller browser window also, I am getting scrolling

![image](https://cloud.githubusercontent.com/assets/161672/16706388/dbfaf30e-45c7-11e6-8f2f-84e9cab1f89b.png)

**Comment by balasankarc** [comment]
എനിക്കുമുണ്ട് ഈ പ്രശ്നം. പക്ഷേ സന്തോഷേട്ടന്റെ പോലെ അത്ര കുറച്ചല്ല സ്ക്രോളബിൾ ഏരിയ. കുറേയുണ്ട് (താഴെ അറ്റാച്ച്മെന്റിൽ കാണാം).

![comicmachine](https://cloud.githubusercontent.com/assets/2379271/16706574/ad1b6dcc-45cf-11e6-9abf-f796ff399b75.png)

Debian Sid/ Firefox 47.0.1.
Resolution: 1366x768

**Comment by hfactor** [comment]
@zmattra : File a bug to github that I Org member can't close an issue which was already closed by someone who is not part of the Org.

**Comment by hfactor** [comment]
@zmattra : File a bug to github that I Org member can't close an issue which was already closed by someone who is not part of the Org.
