### ISSUE TITLE
Update the fonts to latest version

### ISSUE THREAD

**Issue by santhoshtr** [meenaviyal/comicmachine#26]
for example Chilanka.woff is old.File has been renamed to Chilanka-Regular

**Comment by hfactor** [comment]
Similar to #11 
@zmattra please update the fonts to latest versions. 
@santhoshtr Do SMC provide latest fonts in WOFF format? If yes, please share the link.

**Comment by santhoshtr** [comment]
Refer  https://smc.org.in/fonts/css/fonts.css

**Comment by lebmatter** [comment]
Done. 721008fff17445a81c352d4fa9e73959b2a4e988
