### ISSUE TITLE
Rachana is suboptimal for a cartoon as first font option, add more fonts

### ISSUE THREAD

**Issue by santhoshtr** [meenaviyal/comicmachine#27]
Rachana is the first option for the text font. Rachana is too formal font and may not be the right one to give as default. Add more fonts like Meera, Uroob, Karumbi, Suruma

**Comment by hfactor** [comment]
1. Following the standards by keeping 'neutral' font as default font. 
2. Yes, we are adding more fonts. (Similar to #11)

**Comment by zmattra** [comment]
How about making Keraleeyam or Uroob as default?

**Comment by lebmatter** [comment]
Decided to keep Rachana as it is a neutral font.
Added font-face local in ca66b54d20b75768cfaa1421bdc12612b75a10d5
