### ISSUE TITLE
ആപ്പിള്‍ - മലയാളം ഛഗട ഛഗട! :(

### ISSUE THREAD

**Issue by aravindajith** [meenaviyal/comicmachine#3]
മാക് ഓയെസ്സിലെ ക്രോം, സഫാരി ബ്രൗസറുകളില്‍ മലയാളം ഫോണ്ടും സൈസും മാറ്റാന്‍ സാധിക്കുന്നില്ല.. 

<img width="879" alt="screen shot 2016-07-08 at 12 42 36 pm" src="https://cloud.githubusercontent.com/assets/1843300/16680035/b6876076-4509-11e6-8e3b-33822df92f6f.png">

**Comment by hfactor** [comment]
1. We don't have size edit option yet. It's a known bug. 
2. The font embed was working fine in Mac. Was not able to reproduce the bug.
