### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by shahimclt** [meenaviyal/comicmachine#33]
ഇപ്പോള്‍ Browser Tab കാണാന്‍ ഒരു ലുക്ക് ഇല്ല. ഒരു favicon ഇട്ടാല്‍ നന്നായിരിക്കും

**Comment by hfactor** [comment]
@zmattra

**Comment by lebmatter** [comment]
done 6c012b945e6b0a5eb45392e831fae106bf573a58
