### ISSUE TITLE
`Enhancement` Zoom is awkward

### ISSUE THREAD

**Issue by shahimclt** [meenaviyal/comicmachine#35]
currently the hover-zoom on images is a little awkward to use. You can notice this when hovering over an image and then slowly moving mouse pointer to adjacent image. Also, when the last image is zoomed, it is a bit tricky to click the next page button.
![screenshot](https://cloud.githubusercontent.com/assets/8318002/16707927/72b17a4e-45fe-11e6-8cd6-dadfbc6eb029.png)

Making it more like the OS X magnifier effect or trying something like [this](http://www.jqueryrain.com/?zcDohmoE) would be cool.

**Comment by lebmatter** [comment]
Drift is super cool. Will add!

**Comment by shahimclt** [comment]
@zmattra Cool ! btw drift was just a quick example. There may be better options out there.
