### ISSUE TITLE
Click Me യില്‍ ക്ലിക്കി അവിടെ ടൈപ്പ് ചെയ്താല്‍ ഫോണ്ട് മാറ്റാന്‍ പറ്റുന്നില്ല.

### ISSUE THREAD

**Issue by anivar** [meenaviyal/comicmachine#4]
Click Me യില്‍ ക്ലിക്കി അവിടെ ടൈപ്പ് ചെയ്താല്‍ ഫോണ്ട് മാറ്റാന്‍ പറ്റുന്നില്ല.

**Comment by lebmatter** [comment]
Fixed in 4feacf612103727c3a3e054d66544571d8a77eab
