### ISSUE TITLE
Click on an item in the canvas.  And then while typing in the textbox, pressing backspace/delete will result in the deletion of the selected element

### ISSUE THREAD

**Issue by stultus** [meenaviyal/comicmachine#41]
Possible solution :  Remove the active selection while clicking on the textbox

**Comment by shahimclt** [comment]
Recently a delete button functionality was added to delete layers using keyboard button.
The code checked for keycodes 46 ("Delete") and 8 (thats for OsX I suppose). The keycode 8 is causing this issue.

**Comment by stultus** [comment]
Pressing the delete key also will give the same result. this can be fixed by removing the selection while clicking the textbox

**Comment by shahimclt** [comment]
anybody working on this?

**Comment by stultus** [comment]
Currently no. feel free to take it up
