### ISSUE TITLE
[Mac] Using delete key to remove active object causes navigation to previous page

### ISSUE THREAD

**Issue by eternalthinker** [meenaviyal/comicmachine#51]
- This happens when there is a history to the browser tab (chalimachine.com not being the first page opened)
- Need to prevent default behaviour of delete keypress as it doubles up as backspace key in Mac
- Wouldn't want to prevent default behaviour while using delete key for text editing

**Comment by stultus** [comment]
@hfactor please try to reproduce

**Comment by thegeorgeous** [comment]
Fixed by #64
