### ISSUE TITLE
Multiple element selection hinders Delete, Move Up and Move Down actions.

### ISSUE THREAD

**Issue by balasankarc** [meenaviyal/comicmachine#52]
1. ഒരു എലമെന്റിൽ ഡിലീറ്റ് വർക്കും (പേജിലുള്ള ബട്ടണും കീബോർഡ് ഷോർട്ട്കട്ടും വർക്കും).  #2 
2. ഒന്നിൽ കൂടുതൽ എലമെന്റ് സെലക്ട് ചെയ്യാനും പറ്റും.  #19 

പക്ഷേ, ഇതു രണ്ടും കൂടെ ഒരുമിച്ച് വർക്കില്ല. രണ്ട് പടം സെലക്ട് ചെയ്താൽ അവ ഒരുമിച്ച് ഡിലീറ്റ് ചെയ്യാൻ പറ്റില്ല. (പേജിലുള്ള ബട്ടൺ ഞെക്കിയാലും നടക്കില്ല, കീബോർഡ് ഷോർട്ട്കട്ടും നടക്കില്ല)

**Comment by stultus** [comment]
ഞാനീ ബഗ്ഗ് റിപ്പോർട്ടാനാണു ഇപ്പൊ ഗിറ്റ്ഹബ്ബെടുത്തത്   :D

**Comment by stultus** [comment]
Move up & Move down also wont work with multiple element selection.

**Comment by balasankarc** [comment]
So, multiple element selection hinders other processes.

**Comment by shahimclt** [comment]
One more thing, Multiple selection `Shift`+`Click` aanennu evideyenkilum ezhuthi vekkanam. Most people try `Ctrl`+`click`.

**Comment by shahimclt** [comment]
Multiple selection also hinders Download.

![chalistrip](https://cloud.githubusercontent.com/assets/8318002/16780813/ef89929c-4895-11e6-80f6-7bcb6b53f7c4.png)
