### ISSUE TITLE
ഇവ ഉള്‍പ്പെടുത്തിയാല്‍ നന്നായിരിക്കും

### ISSUE THREAD

**Issue by AkhilTMohan** [meenaviyal/comicmachine#7]
ആദ്യം തന്നെ കൊള്ളാം... നൈസ് ഐഡിയ!
Suggesions:
1. TextBox Add ചെയ്യാന്‍ ഒരു ലിങ്ക് ഉള്‍പ്പെടുത്തിയാല്‍ കലക്കും!
2. KeyBoard Shorcuts കൂടി ഉള്‍പ്പെടുത്തിയാല്‍ പൊളിക്കും!
3. TextBox ഉകള്‍ കുറച്ചുകൂടി ഗ്രാഫികലി അഡ്ജസ്റ്റ് ചെയ്യാന്‍ ഉള്ള                           .    വകുപ്പുണ്ടാക്കിയാല്‍ മ്യാരകം!.(ലൈക് cntrl+t in PS) 
4. പിന്നെ ആ പടങ്ങള്‍ ഒക്കെ ഒന്നു ഗ്രൂപ്പ് ചെയ്താല്‍ മുങ്ങിത്തപ്പല്‍ ഒഴിവാക്കാമായിരുന്നു! (ie:ഭീഭല്‍സം,കരുണം.. മുതലായവ)
5. ആര്‍ട്ട് ബോര്‍ഡിന്റെ സൈസ് ചെറുതാക്കുമ്പോള്‍ whole Content കൂടി ഒപ്പം ചെറുതായല്‍ നന്നായിരുന്നു!

**Comment by hfactor** [comment]
@AkhilTMohan :  We are working on a better UI for text edit part. (#1) also (#4) is under implementation.
5th one is tough, it's all raster images and text, we will look into it anyway.

**Comment by hfactor** [comment]
Breaking this issue to multiple issues, for ease of following.

**Comment by hfactor** [comment]
All suggested changes are duplicate of other issues. Hence editing the issue title.

**Comment by hfactor** [comment]
Closing the ticket since 1 to 4 issues are duplicate of existing issues. 
For suggestion No.5 : I don't think it would usable for every condition, and also Scaling image make sense only when it's uniformly scaled. Also, affects the quality as collection contain Raster images.
